# 配置文件 for 自动标签脚本

# 输入文件路径
input_file:
  path: "similar_words/from_zhu/law_similarity_classified_8_19.xlsx"
  sheet_name: "法制era1"
  column_name: "word" # 词语所在的列名

# 标签定义文件路径
tag_definitions_path: "topic_word/tag_define/legal_tags.json"

# 词向量模型路径
# -------------------------
# 请选择以下一个模型路径使用。取消注释你想要使用的那一个，并注释掉另一个。

# 选项 A: 项目内微调模型 (Fine-tuned Model)
word_vector_model_path: "models/fine_tuned_vectors_flexible/Era1_1978-1996_wordvectors.kv"

# 选项 B: 通用预训练模型 (General Pre-trained Model)
# word_vector_model_path: "/data/userdata/fangshikai/gensim-data/vectors/chinese_vectors.kv"


# 输出文件配置
output_file:
  directory: "topic_word"
  filename_prefix: "tagged_法制era1"
  formats: ["csv", "xlsx"] # 支持 "csv" 和 "xlsx"

# 标签处理配置
tagging_strategy: "similarity" # 未来可扩展为 "llm" 等

# 模型相关参数 (未来可用于LLM等)
# model_params:
#   api_key: "YOUR_API_KEY"
#   model_name: "gpt-4" 